In [1]:
import pandas as pd

In [17]:
data = pd.read_csv('ratings.csv')
data.head()

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [91]:
movies = data[['movieId','rating']]

filters = movies[ (movies['movieId']) & (movies['rating']==5.0) ]

filters['movieId'].value_counts().head(1)

2571    25482
Name: movieId, dtype: int64

In [152]:
countries = pd.read_csv('power.csv')
countries.head()

   country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [141]:
data_f = countries [
    ((countries['country'] == 'Lithuania') | 
    (countries['country'] == 'Estonia' ) | 
    (countries['country'] == 'Latvia')) &
    ((countries['category'] == 4)|
    (countries['category'] == 12)|
    (countries['category'] == 21))&
    ((countries['year'] == 2005) |
     (countries['year'] == 2006) |
     (countries['year'] == 2007) |
     (countries['year'] == 2008) |
     (countries['year'] == 2009) |
     (countries['year'] == 2010)) &
     ((countries['quantity']>= 0))
]

sum(data_f['quantity'])

240580.0

In [165]:
pd.read_html('https://www.finanz.ru/valyuty/v-realnom-vremeni',  encoding='utf-8') [1]

,Unnamed: 0,Рубль,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
0,NaN,GBP/RUB,1002194,-,1016203,"-1,38 %",-14009,20:56:00
1,NaN,EUR/RUB,910350,-,927685,"-1,87 %",-17335,20:55:00
2,NaN,USD/RUB,776295,-,790142,"-1,75 %",-13847,20:55:00
3,NaN,JPY/RUB,07359,-,07477,"-1,58 %",-00118,20:56:00
4,NaN,CNY/RUB,114314,-,115916,"-1,38 %",-01603,20:55:00
5,NaN,CHF/RUB,843069,-,858945,"-1,85 %",-15875,20:56:00
6,NaN,Евро,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
7,NaN,EUR/USD,11727,-,11742,"-0,12 %",-00015,20:55:00
8,NaN,EUR/GBP,09084,-,09130,"-0,51 %",-00046,20:55:00
9,NaN,EUR/JPY,1237200,-,1240600,"-0,27 %",-03400,20:55:00
10,NaN,EUR/CHF,10799,-,10802,"-0,03 %",-00003,20:55:00
11,NaN,Доллар США,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
12,NaN,USD/EUR,08527,-,08517,"0,12 %",00010,20:56:00
13,NaN,USD/GBP,07746,-,07775,"-0,38 %",-00030,20:56:00
14,NaN,USD/JPY,1054960,-,1056680,"-0,16 %",-01720,20:55:00
15,NaN,USD/CHF,09208,-,09197,"0,11 %",00011,20:55:00
16,NaN,Японская иена,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
17,NaN,JPY/EUR (100:1),08100,-,08100,"0,28 %",00000,20:55:00
18,NaN,JPY/GBP,00073,-,00074,"-0,20 %",00000,20:56:00
19,NaN,JPY/USD,00095,-,00095,"0,18 %",00000,20:55:00
20,NaN,JPY/CHF (100:1),08700,-,08700,"0,24 %",00000,20:55:00
21,NaN,Фунт стерлингов,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
22,NaN,GBP/USD,12910,-,12861,"0,38 %",00049,20:55:00
23,NaN,GBP/JPY,1361902,-,1359073,"0,21 %",02828,20:56:00
24,NaN,GBP/EUR,11008,-,10953,"0,50 %",00055,20:55:00
25,NaN,GBP/CHF,11888,-,11832,"0,47 %",00056,20:55:00
26,NaN,Швейцарский франк,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
27,NaN,GBP/CHF,11888,-,11832,"0,47 %",00056,20:55:00
28,NaN,EUR/CHF,10799,-,10802,"-0,03 %",-00003,20:55:00
29,NaN,JPY/CHF (100:1),08700,-,08700,"0,24 %",00000,20:55:00
30,NaN,USD/CHF,09208,-,09197,"0,11 %",00011,20:55:00
31,NaN,Украинская гривна,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
32,NaN,EUR/UAH,331888,-,332714,"-0,25 %",-00825,20:56:00
33,NaN,USD/UAH,283000,-,283366,"-0,13 %",-00366,20:55:00
34,NaN,CHF/UAH,307342,-,308040,"-0,23 %",-00698,20:55:00
35,NaN,GBP/UAH,365353,-,364436,"0,25 %",00917,20:56:00