In [86]:
import pandas as pd

In [2]:
log = pd.read_csv('visit_log.csv', sep = ';')
log.head(5)

,timestamp,visit_id,url,region,user_id,traffic_source
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex

In [6]:
log.loc[(log.traffic_source == 'yandex') | (log.traffic_source == 'google'), 'source_type'] = 'organic' 
log.loc[(log.traffic_source == 'email') & (log.region =='Russia'), 'source_type'] = 'ad' 
log.loc[(log.traffic_source == 'paid') & (log.region =='Russia'), 'source_type'] = 'ad' 
log.loc[(log.traffic_source == 'email') & (log.region !='Russia'), 'source_type'] = 'other' 
log.loc[(log.traffic_source == 'paid') & (log.region !='Russia'), 'source_type'] = 'other' 

log.head(25)

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,organic
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,NaN
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,organic
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,organic
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,organic
5,1549980742,8855508aad,https://host.ru/df646c3676cc259fa0,Russia,fc43898e47,yandex,organic
6,1549980742,b0f66adc83,https://host.ru/b8b58337d272ee7b15,Russia,13fc55e781,paid,ad
7,1549980754,837885c8f8,https://host.ru/108ce4b365afb7b88e,Russia,cb5082b6f6,direct,NaN
8,1549980760,af5570f5a1,https://host.ru/3004a8273caeef2867,China,45664f7af2,direct,other
9,1549980765,3e7077fd2f,https://host.ru/df646c3676cc259fa0,Russia,6f9de8c8b6,email,ad
10,1549980777,01d448afd9,https://host.ru/a5dda93e70318570c0,India,27e76a4a80,direct,other
11,1549980785,71b6c1d538,https://host.ru/c8d9213a31839f9a3a,Ukraine,3b13701488,google,organic
12,1549980789,15ec7bf0b5,https://host.ru/8e88d4703848cc0ec4,Russia,6d1d81f7f8,paid,ad
13,1549980792,dd46c3eebb,https://host.ru/3004a8273caeef2867,China,7e301c8c41,direct,other
14,1549980793,e7ecebbc59,https://host.ru/05e41944dd85a900a6,Belarus,ac52dedc3b,direct,other
15,1549980797,5322fecfc9,https://host.ru/4adc8a29b212051b04,Belarus,9a45d98867,paid,other
16,1549980801,374708fff7,https://host.ru/39fa884393666d45fc,Russia,e9bd59e22d,google,organic
17,1549980807,0a88111852,https://host.ru/2fcb223266880ccf57,Ukraine,a2ba8fa3db,paid,other
18,1549980814,60daa3a5f7,https://host.ru/ef57543002ce2a0f2a,Belarus,72cb10fb5c,direct,other
19,1549980816,d6fd62f5ce,https://host.ru/f1eb4601740d627ab0,Belarus,7269dcd869,direct,other
20,1549980816,de47c9b27e,https://host.ru/8fe7c39e5c598bbc54,Ukraine,2f25b6e26a,email,other
21,1549980823,c90232586b,https://host.ru/da83c74e35e7806fe0,Ukraine,a00405d70c,google,organic
22,1549980827,6a4875ddac,https://host.ru/f2297425e1328e9e35,Ukraine,ea1bf97284,yandex,organic
23,1549980839,015275e61f,https://host.ru/c8d9213a31839f9a3a,Russia,21bdc57777,email,ad
24,1549980842,9d908ecfb6,https://host.ru/ae8a036d7f44d0bcd9,China,583b1a1636,direct,other

In [50]:
url = pd.read_table('URLs.txt')

url

                                                  url
0                                             /world/
1                                            /latest/
2                                       /?updated=top
3   /politics/36188461-s-marta-zhizn-rossiyan-susc...
4   /world/36007585-tramp-pridumal-kak-reshit-ukra...
..                                                ...
88  /cis/35984145-kreml-prokommentiroval-soobschen...
89  /video/36071019-olimpiyskie-obekty-rio-prevrat...
90  /science/36151301-nazvano-posledstvie-zloupotr...
91  /incidents/36027330-vospitatelnitsu-zatravili-...
92  /world/36103095-dominikanskih-zhurnalistov-ubi...

[93 rows x 1 columns]

In [52]:
url[url.url.str.contains(r'\w+\d+\-')]

                                                  url
3   /politics/36188461-s-marta-zhizn-rossiyan-susc...
4   /world/36007585-tramp-pridumal-kak-reshit-ukra...
5   /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
6   /video/36001498-poyavilis-pervye-podrobnosti-g...
7   /world/36007585-tramp-pridumal-kak-reshit-ukra...
..                                                ...
88  /cis/35984145-kreml-prokommentiroval-soobschen...
89  /video/36071019-olimpiyskie-obekty-rio-prevrat...
90  /science/36151301-nazvano-posledstvie-zloupotr...
91  /incidents/36027330-vospitatelnitsu-zatravili-...
92  /world/36103095-dominikanskih-zhurnalistov-ubi...

[84 rows x 1 columns]

In [54]:
pip install git+https://github.com/nlpub/pymystem3

Collecting git+https://github.com/nlpub/pymystem3
  Cloning https://github.com/nlpub/pymystem3 to c:\users\user\appdata\local\temp\pip-req-build-gvh7x_52
Requirement already satisfied (use --upgrade to upgrade): pymystem3==0.2.0 from git+https://github.com/nlpub/pymystem3 in c:\users\user\anaconda3\lib\site-packages
Requirement already satisfied: requests in c:\users\user\anaconda3\lib\site-packages (from pymystem3==0.2.0) (2.24.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\anaconda3\lib\site-packages (from requests->pymystem3==0.2.0) (2020.6.20)Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: idna<3,>=2.5 in c:\users\user\anaconda3\lib\site-packages (from requests->pymystem3==0.2.0) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\user\anaconda3\lib\site-packages (from requests->pymystem3==0.2.0) (1.25.9)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\user\anaconda3\lib\site-packages (from requests->pymystem3==0.2.0) (3.0.4)
Building wheels for collected packages: pymystem3
  Building wheel for pymystem3 (setup.py): started
  Building wheel for pymystem3 (setup.py): finished with status 'done'
  Created wheel for pymystem3: filename=pymystem3-0.2.0-py3-none-any.whl size=8033 sha256=9bfc958d562cae8a0a02569440bc19a37e5b96ee870c6352808326cbbe89c319
  Stored in directory: C:\Users\user\AppData\Local\Temp\pip-ephem-wheel-cache-ucx9tbru\wheels\9a\a7\9f\1e6160c89d9005d7be2218364a9afaf5a96f38624eaace7119
Successfully built pymystem3

  Running command git clone -q https://github.com/nlpub/pymystem3 'C:\Users\user\AppData\Local\Temp\pip-req-build-gvh7x_52'

In [87]:
from pymystem3 import Mystem

In [89]:
data = pd.DataFrame({
    'keyword': ['курс гривны к рублю', 'доллары в рубли', '100 долларов в рублях', 'курс рубля'],
    'shows': [125076, 114173, 97534, 53546],
})

data

                 keyword   shows
0    курс гривны к рублю  125076
1        доллары в рубли  114173
2  100 долларов в рублях   97534
3             курс рубля   53546

In [58]:
m = Mystem()

,keyword,shows,lemmas
0,курс гривны к рублю,125076,<generator object <genexpr> at 0x00000292340CE...
1,доллары в рубли,114173,<generator object <genexpr> at 0x00000292340CE...
2,100 долларов в рублях,97534,<generator object <genexpr> at 0x00000292340CE...
3,курс рубля,53546,<generator object <genexpr> at 0x00000292340CE...

In [148]:
def lemm(word):
    return(' '.join(m.lemmatize(word)))

In [149]:
data['lemmas'] = data['keyword'].apply(lemm)
data

                 keyword   shows                        lemmas
0    курс гривны к рублю  125076  курс   гривна   к   рубль \n
1        доллары в рубли  114173         доллар   в   рубль \n
2  100 долларов в рублях   97534   100   доллар   в   рубль \n
3             курс рубля   53546               курс   рубль \n